version: '3'
services:
  frontend:
    image: caneplayz/tennisrankings-frontend
    build:
      context: ./TennisRankings
      dockerfile: Dockerfile.dev
    ports:
      - "5000:80"
  api:
    image: caneplayz/tennisrankings-api
    build:
      context: ./TennisRankings.API
      dockerfile: Dockerfile.dev
    ports:
      - "8000:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
