version: '3.8'
services:
  frontend:
    image: caneplayz/tennisrankings-frontend
    ports:
      - "8080:80"
  api:
    image: caneplayz/tennisrankings-api
    environment:
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5000:80"
