version: '3.8'

services:
  green-frontend:
    image: caneplayz/tennisrankings-frontend:latest
    environment:
      - ACTIVE_ENVIRONMENT=green
    ports:
      - "8082:8080"

  green-api:
    image: caneplayz/tennisrankings-api:latest

  green-database:
    image: caneplayz/tennisrankings-database:latest
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=rankings-green
    volumes:
      - green-postgres-database:/var/lib/postgresql/data

volumes:
  green-postgres-database:
