version: '3.8'

services:
  blue-frontend:
    image: caneplayz/tennisrankings-frontend:latest
    environment:
      - ACTIVE_ENVIRONMENT=blue
    ports:
      - "8081:8080"

  blue-api:
    image: caneplayz/tennisrankings-api:latest

  blue-database:
    image: caneplayz/tennisrankings-database:latest
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=rankings-blue
    volumes:
      - blue-postgres-database:/var/lib/postgresql/data

volumes:
  blue-postgres-database:
