version: '3.8'

services:
  dev-frontend:
    image: caneplayz/tennisrankings-frontend
    build:
      context: ../TennisRankings
      dockerfile: Dockerfile
    environment:
      - ACTIVE_ENVIRONMENT=dev
    ports:
      - "8080:80"

  dev-api:
    image: caneplayz/tennisrankings-api
    build:
      context: ../TennisRankings.API
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80

  dev-database:
    image: caneplayz/tennisrankings-database
    build:
      context: ../PostgreSQL
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=rankings
    volumes:
      - postgres-database:/var/lib/postgresql/data

volumes:
  postgres-database:
